apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: healthsense
spec:
  type: LoadBalancer
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080