apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: healthsense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: gcr.io/healthsense-platform/airflow-custom:latest
          command: ["bash", "-c"]
          args:
            - |
              airflow db migrate &&
              airflow users create \
                --username admin \
                --password admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com &&
              airflow webserver --port 8080 --host 0.0.0.0
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: sql_alchemy_conn
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi