apiVersion: v1
kind: Service
metadata:
  name: healthsense-api-service
  namespace: healthsense
spec:
  type: LoadBalancer
  selector:
    app: healthsense-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000